config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1 class="text-center">All our flats (<%= @flats.count %>)</h1>

<div class="container">
  <div class="row  p-0 d-flex justify-content-between">
    <% @flats.each do |flat| %>
      <div class="flat-card col-md-4 flex-column">
          <div class="flat-card-image" style="background-image: url('https://source.unsplash.com/random/2400*180')"></div>
            <div class="flat-card-content">
              <div><b><%= link_to flat.name, flat %></b></div>
              <div><%= flat.description %></div>
              <div class="flat-address"><i class="fa-solid fa-location-dot"></i>  <%= flat.address %>.</div>
            </div>
            <div class="youn d-flex justify-content-around">
              <div>
                <i class="fa-solid fa-dollar-sign"></i> <%= flat.price_per_night %>
              </div>
              <div>
                <i class="fa-solid fa-user"></i> <%= flat.number_of_guests %>
              </div>
            </div>

      </div>
  <br>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit %>
<% end %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<h5><em><%= @flat.description %></em></h5>
<p><%= @flat.address %></p>
<p><%= @flat.price_per_night %></p>
<p><%= @flat.number_of_guests %></p>

<p><%= link_to "See all flats", flats_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Simple Airbnb</a>
    <div class="ms-auto flex">
      <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>